exdata <- read.table("exdata-data-household_power_consumption/household_power_consumption.txt", header = TRUE, sep = ";")
exsub <- subset(exdata, (exdata$Date == "1/2/2007" | exdata$Date == "2/2/2007"))
exsub$Datetime <- paste(exsub$Date, exsub$Time, sep=" ")
exsub$Datetime <- as.POSIXct(exsub$Datetime, format = "%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
plot(exsub$Datetime,as.numeric(as.character(exsub$Global_active_power)),type="l",xlab = "",ylab = "Global Active Power")
plot(exsub$Datetime,as.numeric(as.character(exsub$Voltage)),type="l",xlab = "datetime",ylab = "Voltage")
plot(exsub$Datetime,as.numeric(as.character(exsub$Sub_metering_1)),type="l",xlab = "",ylab = "Energy sub metering")
lines(exsub$Datetime,as.numeric(as.character(exsub$Sub_metering_2)),type="l",col="red")
lines(exsub$Datetime,as.numeric(as.character(exsub$Sub_metering_3)),type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1),col=c("black", "red", "blue"),bty = "n")
plot(exsub$Datetime,as.numeric(as.character(exsub$Global_reactive_power)),type="l",xlab = "datetime",ylab = "Global_reactive_power")
dev.off()